default: &default
  id: <%= ENV["FACEBOOK_API_ID"] %>
  secret: <%= ENV["FACEBOOK_API_SECRET"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
